name: parcellate
channels:
  - defaults
dependencies:
  - pip
  - python
  - tk
  - pip:
    - fast-poibin
    - h5py
    - matplotlib
    - nibabel
    - nilearn
    - git+https://github.com/nipy/nitransforms.git@master
    - numpy
    - pandas
    - pillow
    - pymatreader
    - pyyaml
    - scikit-learn
    - scipy
    - seaborn
